"""add_logo_url_to_stocks

Revision ID: 1f96a806ed5a
Revises: 4b110ff802ff
Create Date: 2026-04-07 12:19:23.073217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f96a806ed5a'
down_revision: Union[str, Sequence[str], None] = '4b110ff802ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'logo_url')
    # ### end Alembic commands ###
